---
- name: "Update apt cache"
  ansible.builtin.apt:
    update_cache: true

- name: "Install required packages"
  ansible.builtin.apt:
    name: "{{ pkglist }}"
    update_cache: true
    autoremove: true
    state: present
  notify: 'Restart ddclient'
