---
- name: "Enable EPEL repo"
  ansible.builtin.package:
    name: "epel-release"
    state: present
  when: enable_epel is defined and enable_epel

- name: "Install required packages"
  ansible.builtin.package:
    name: "{{ pkglist }}"
    state: present
  notify: 'Restart ddclient'
