---
- name: Converge
  hosts: all
  connection: local
  become: true
  vars:
    ddclient_provider: "dyndns2"
    ddclient_domains:
      - "yourdomain.tld"
    ddclient_login: "you login"
    ddclient_password: "your password"
  roles:
    - role: "ansible_role_ddclient"
